Mall.Web.Back/Controllers/GoodsController.cs
using Mall.Service.DataBase;
using Mall.Service.Models;
using Mall.Service.Services;
using Mall.Service.Services.Enterprise;
using Mall.Web.Back.Filter;
using Mall.Web.Back.ViewModel;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mall.Web.Back.Controllers
{
    public class GoodsController : Controller
    {
        private GoodsManageService _goodsManageService = new GoodsManageService();
        private GoodsService _goodsService = new GoodsService();
        #region 商品管理
        [HttpGet]
        [PermissionAuthorize("AddGoods")]
        public ActionResult CreateGoods()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetGoodsSimpleInfo(int goodsId)
        {
            GoodsInfo goods = _goodsService.GetGoodsByGoodsId(goodsId);
            GoodsInfoViewModel goodsDTO = DataGoodToDTO(new List<GoodsInfo> { goods }).ElementAt(0);
            return PartialView(goodsDTO);
        }

        #region 添加商品
        [HttpPost]
        [PermissionAuthorize("AddGoods")]
        public int CreateGoods(string name, string count, string price,
            string detail, DateTime? publicationDate, string freight = "+0",
            string author = null, string press = null)
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return new int();
            }

            int countNumber = Convert.ToInt16(count.Substring(1));
            double newPrice = Convert.ToDouble(price.Substring(1));
            double newFreight = Convert.ToDouble(freight.Substring(1));

            int result = _goodsManageService.CreateGoods(employee.EmployeeId,name, countNumber, newPrice, detail,
                newFreight, publicationDate, author, press);
            return result;
        }

        [HttpPost]
        [PermissionAuthorize("AddGoods")]
        public ActionResult CreateGoodsImg(int goodsId)
        {
            HttpFileCollection filess = System.Web.HttpContext.Current.Request.Files;

            foreach (var key in filess.AllKeys)
            {
                HttpPostedFile file = filess[key];
                if (string.IsNullOrEmpty(file.FileName) == false)
                {
                    if(SaveImage(file, goodsId))
                    {
                        return new EmptyResult();
                    }
                    return HttpNotFound();
                }
                return HttpNotFound();
            }
            return new EmptyResult();
        }

        private bool SaveImage(HttpPostedFile file,int goodsId)
        {
            if (!_goodsManageService.IsImageFull(goodsId))
            {
                string now = DateTime.Now.ToString("yyyy-MM-ddHHmmss");
                string path = "Mall.Web.Goods/Goods/" + now + file.FileName;
                file.SaveAs("F:/网站部署/MallImg/" + path);
                _goodsManageService.AddGoodsImage(goodsId, path);
                return true;
            }
            return false;
        }
        #endregion

        #region 上下架
        [HttpGet]
        [PermissionAuthorize("OnShelves")]
        public ActionResult OnTheShelves(int page = 1,int pageSize = 10)
        {
            List<GoodsInfo> goods = _goodsService.GetGoodsByGoodsState((int)StateOfGoods.State.OffShelves);
            IPagedList<GoodsInfoViewModel> goodsDTO = DataGoodToDTO(goods).ToPagedList(page,pageSize);
            return View(goodsDTO);
        }

        [HttpPost]
        [PermissionAuthorize("OnShelves")]
        public bool OnTheShelves(int goodsId)
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return false;
            }
            var result = _goodsManageService.OnShelvesByGoodsId(employee.EmployeeId,goodsId);
            return result;
        }

        [HttpGet]
        [PermissionAuthorize("OffShelves")]
        public ActionResult OffTheShelves(int page = 1, int pageSize = 10)
        {
            List<GoodsInfo> goods = _goodsService.GetGoodsByGoodsState((int)StateOfGoods.State.OnShelves);
            IPagedList<GoodsInfoViewModel> goodsDTO = DataGoodToDTO(goods).ToPagedList(page, pageSize);
            return View(goodsDTO);
        }

        [HttpPost]
        [PermissionAuthorize("OffShelves")]
        public bool OffTheShelves(int goodsId)
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return false;
            }
            var result = _goodsManageService.OffShelvesByGoodsId(employee.EmployeeId,goodsId);
            return result;
        }
        #endregion

        #region 修改商品
        [HttpGet]
        public ActionResult Search(string search)
        {
            List<GoodsInfo> goods = _goodsService.GetAllGoods();
            List<GoodsInfoViewModel> goodsDTO = DataGoodToDTO(goods).Where(g => g.GoodsName.Contains(search)).ToList();
            return PartialView(goodsDTO);
        }

        [HttpGet]
        public ActionResult GoodsInfoDetails(int goodsId)
        {
            GoodsInfo goods = _goodsService.GetGoodsByGoodsId(goodsId);
            GoodsInfoViewModel goodsDTO = DataGoodToDTO(new List<GoodsInfo> { goods }).ElementAt(0);
            return PartialView(goodsDTO);
        }

        [HttpGet]
        public ActionResult GoodsImgList(int goodsId)
        {
            List<Image> imgs = _goodsService.GetImgsByGoodsId(goodsId);
            List<ImageViewModel> imgsDTO = imgs.Select(i => new ImageViewModel
            {
                GoodsId = goodsId,
                ImageId = i.ImageId,
                ImageSrc = i.ImageSrc
            }).ToList();
            return PartialView(imgsDTO);
        }

        [HttpGet]
        [PermissionAuthorize("ModifyGoods")]
        public ActionResult GoodsEdit()
        {
            List<GoodsInfo> goods = _goodsService.GetAllGoods();
            List<GoodsInfoViewModel> goodsDTO = DataGoodToDTO(goods);
            return View(goodsDTO);
        }

        [HttpPost]
        [PermissionAuthorize("ModifyGoods")]
        public bool GoodsEdit(int goodsId, string name, string price,
            string detail, DateTime? publicationDate, string freight = "+0",
            string author = null, string press = null)
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return false;
            }
            double newPrice = Convert.ToDouble(price.Substring(1));
            double newFreight = Convert.ToDouble(freight.Substring(1));

            var result = _goodsManageService.ModifyGoodsInfo(employee.EmployeeId,goodsId, name, newPrice, detail,
                publicationDate, newFreight, author, press);
            return true;
        }
        #endregion

        #region 库存
        [HttpGet]
        [PermissionAuthorize("NewStorage")]
        public ActionResult GoodsStock(int page = 1, int pageSize = 10)
        {
            List<GoodsInfo> goods = _goodsService.GetAllGoods();
            IPagedList<GoodsInfoViewModel> goodsDTO = DataGoodToDTO(goods).ToPagedList(page, pageSize);
            return View(goodsDTO);
        }

        [HttpPost]
        [PermissionAuthorize("NewStorage")]
        public bool ModifyGoodsStock(int goodsId,string count)
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return false;
            }
            int newCount = Convert.ToInt16(count.Substring(1));
            var result = _goodsManageService.ModifyGoodsStockByGoodsId(employee.EmployeeId,goodsId,newCount);
            return result;
        }

        [HttpPost]
        [PermissionAuthorize("NewStorage")]
        public bool DeletGoodsImgs(int[] imageIds)
        {
            var result =  _goodsManageService.DeletGoodsImage(imageIds);
            return result;
        }
        #endregion
        #endregion

        public static List<GoodsInfoViewModel> DataGoodToDTO(List<GoodsInfo> goods)
        {
            if (goods == null)
            {
                return new List<GoodsInfoViewModel>();
            }
            List<GoodsInfoViewModel> goodDTO = goods.Select(g => new GoodsInfoViewModel
            {
                GoodsId = g.GoodsId,
                GoodsName = g.GoodsName,
                Price = g.Price,
                Stock = g.Stock,
                Details = g.Details,
                SalesNumber = g.SalesNumber,
                CommentNumber = g.CommentNumber,
                State = g.State,
                CreateTime = g.CreateTime.ToString("yyyy-MM-dd HH-mm-ss"),
                ShelfTime = g.ShelfTime == null ? "0000-00-00 00-00-00" : g.ShelfTime.Value.ToString("yyyy-MM-dd HH-mm-ss"),
                UnderShelfTime = g.UnderShelfTime == null ? "0000-00-00 00-00-00" : g.UnderShelfTime.Value.ToString("yyyy-MM-dd HH-mm-ss"),
                IsDelete = g.IsDelete,
                Author = g.Author,
                Press = g.Press,
                PublicationDate = g.PublicationDate == null ? "0000-00-00" : g.PublicationDate.Value.ToString("yyyy-MM-dd"),
                Freight = g.Freight,
                ImageUrl = g.Image.Count == 0 ? "" : g.Image.ElementAt(0).ImageSrc,
            }).ToList();
            return goodDTO;
        }
    }
}

Mall.Web.Back/Views/Order/AllOrders.cshtml
@model IPagedList<Mall.Web.Back.ViewModel.OrderViewModel>
@using PagedList.Mvc
@using PagedList

@{
    ViewBag.Title = "所有订单";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}

<section class="content-header">
    <h1><i class="fa fa-reorder"></i>所有订单</h1>
</section>
<section class="content">
    <div class="order-wrapper">
        <div class="order-title">
            <ul>
                <li class="order-list">编号</li>
                <li class="order-id">订单编号</li>
                <li class="order-good-name">商品名</li>
                <li class="order-good-id">商品Id</li>
                <li class="order-price">单价</li>
                <li class="order-count">数量</li>
                <li class="order-freight">运费</li>
                <li class="order-totla">总价</li>
                <li class="order-state">状态</li>
                <li class="order-client-remark">买家备注</li>
                <li class="order-action">操作</li>
                <li class="order-createtime">创建时间</li>
            </ul>
        </div>
        <div class="order-content">
            @Html.Partial("ViewComponents/_OrderList", Model)
            <div class="order-list-contorl">
                每页 @Model.PageSize 条记录,共 @Model.Count 条记录,共 @Model.PageCount 页,当前第 @Model.PageNumber 页
                <div class="list-contorl-button">
                    @Html.PagedListPager(Model, page => Url.Action("AllOrders", new { page }))
                </div>
            </div>
        </div>
    </div>
</section>
@Html.Partial("ViewComponents/_ModifyRemark")
@Html.Partial("Admin/_ManageConfirm")
@section css{
    @Styles.Render("~/Css/Order/Orders.css")
}
@section scripts{
    @Scripts.Render("~/JS/Order/Orders.js")
    @Scripts.Render("~/JS/Shared/ManageConfirm.js")
    @Scripts.Render("~/JS/Shared/layer_open_tip.js")
}

Mall.Web.Back/Views/Order/FinishedOrder.cshtml
@model PagedList.IPagedList<Mall.Web.Back.ViewModel.OrderViewModel>
@using PagedList.Mvc
@using PagedList

@{
    ViewBag.Title = "完成交易";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}

<section class="content-header">
    <h1><i class="fa fa-reorder"></i>交易完成</h1>
</section>
<section class="content">
    <div class="order-wrapper">
        <div class="order-title">
            @Html.Partial("_OrderTitle")
        </div>
        <div class="order-content">
            @Html.Partial("ViewComponents/_OrderList", Model)
            <div class="order-list-contorl">
                每页 @Model.PageSize 条记录,共 @Model.Count 条记录,共 @Model.PageCount 页,当前第 @Model.PageNumber 页
                <div class="list-contorl-button">
                    @Html.PagedListPager(Model, page => Url.Action("FinishedOrder", new { page }))
                </div>
            </div>
        </div>
    </div>
</section>
@Html.Partial("ViewComponents/_ModifyRemark")
@Html.Partial("Admin/_ManageConfirm")
@section css{
    @Styles.Render("~/Css/Order/Orders.css")
}
@section scripts{
    @Scripts.Render("~/JS/Order/Orders.js")
}

Mall.Web.Back/Views/Order/GetBuyerInfo.cshtml
@model Mall.Web.Back.ViewModel.UserViewModel

<div class="replyevaluate-buyer-info">
    <h4 class="replyevaluate-title">买家</h4>
    <div>
        <img src="@Model.Photo" />
        <span>@Model.NickName</span>
    </div>
</div>

Mall.Web.Back/Views/Order/GetOrderInfo.cshtml
@model Mall.Web.Back.ViewModel.OrderViewModel

<h4 class="replyevaluate-title">订单信息</h4>
<table>
    <tr>
        <td>订单编号:&emsp;<span>@Model.OrderId</span></td>
        <td>下单时间:&emsp;<span>@Model.CreateTime</span></td>
    </tr>
    <tr>
        <td>发货时间:&emsp;<span>@Model.DeliveryTime</span></td>
        <td>收货时间:&emsp;<span>@Model.ReceiptTime</span></td>
        <td>成交时间:&emsp;<span>@Model.ReceiptTime</span></td>
    </tr>
</table>

Mall.Web.Back/Views/Order/RefundConfirm.cshtml
@model PagedList.IPagedList<Mall.Web.Back.ViewModel.OrderViewModel>
@using PagedList.Mvc
@using PagedList

@{
    ViewBag.Title = "退款处理";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}


<section class="content-header">
    <h1><i class="fa fa-reorder"></i>退款申请</h1>
</section>
<section class="content">
    <div class="order-wrapper">
        <div class="order-title">
            @Html.Partial("ViewComponents/_OrderTitle")
        </div>
        <div class="order-content">
            @Html.Partial("ViewComponents/_OrderList", Model)
            <div class="order-list-contorl">
                每页 @Model.PageSize 条记录,共 @Model.Count 条记录,共 @Model.PageCount 页,当前第 @Model.PageNumber 页
                <div class="list-contorl-button">
                    @Html.PagedListPager(Model, page => Url.Action("AllOrders", new { page }))
                </div>
            </div>
        </div>
    </div>
</section>
@Html.Partial("ViewComponents/_ModifyRemark")
@Html.Partial("Admin/_ManageConfirm")
@section css{
    @Styles.Render("~/Css/Order/Orders.css")
}
@section scripts{
    @Scripts.Render("~/JS/Order/Orders.js")
}

Mall.Web.Back/Views/Order/ReplyEvaluate.cshtml
@model Mall.Web.Back.ViewModel.CommentViewModel

@{
    ViewBag.Title = "回复评价";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}

<section class="content-header">
    <h1><i class="fa fa-mail-reply"></i>回复评价</h1>
</section>
<section class="content">
    <div class="replyevaluate-all">
        <div class="replyevaluate-goods-info">
            @Html.Action("GetGoodsSimpleInfo", "Goods", new { goodsId = Model.GoodsId })
        </div>
        <div class="replyevaluate-buyer">
            @Html.Action("GetBuyerInfo", "Order", new { orderId = Model.OrderId })
            <div class="replyevaluate-buyer-message">
                <h4 class="replyevaluate-title">留言</h4>
                <div>
                    <p>
                        @Model.CommentDetail
                    </p>
                </div>
            </div>
        </div>
        <div class="replyevaluate">
            <div class="replyevaluate-order">
                @Html.Action("GetOrderInfo", "Order",new { orderId = Model.OrderId})
            </div>
            <form action="/Order/ReplyEvaluate" method="post">
                <div class="replyevaluate-reply">
                    <h4 class="replyevaluate-title">回复评价</h4>
                    <input name="orderId" type="hidden" value="@Model.OrderId"/>
                    <input name="commentId" type="hidden" value="@Model.CommentId" />
                    <textarea name="replyContent"></textarea>
                    <button type="submit">立即回复</button>
                </div>
            </form>
        </div>
    </div>
</section>
@section css{
    @Styles.Render("~/Css/Order/ReplyEvaluate.css")
}

Mall.Web.Back/Views/Order/ReturnConfirm.cshtml
@model PagedList.IPagedList<Mall.Web.Back.ViewModel.OrderViewModel>
@using PagedList.Mvc
@using PagedList

@{
    ViewBag.Title = "退货处理";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}


<section class="content-header">
    <h1><i class="fa fa-reorder"></i>退货申请</h1>
</section>
<section class="content">
    <div class="order-wrapper">
        <div class="order-title">
            @Html.Partial("ViewComponents/_OrderTitle")
        </div>
        <div class="order-content">
            @Html.Partial("ViewComponents/_OrderList", Model)
            <div class="order-list-contorl">
                每页 @Model.PageSize 条记录,共 @Model.Count 条记录,共 @Model.PageCount 页,当前第 @Model.PageNumber 页
                <div class="list-contorl-button">
                    @Html.PagedListPager(Model, page => Url.Action("ReturnConfirm", new { page }))
                </div>
            </div>
        </div>
    </div>
</section>
@Html.Partial("ViewComponents/_ModifyRemark")
@Html.Partial("Admin/_ManageConfirm")
@section css{
    @Styles.Render("~/Css/Order/Orders.css")
}
@section scripts{
    @Scripts.Render("~/JS/Order/Orders.js")
}

Mall.Web.Back/Views/Order/ToAccept.cshtml
@model PagedList.IPagedList<Mall.Web.Back.ViewModel.OrderViewModel>
@using PagedList.Mvc
@using PagedList

@{
    ViewBag.Title = "接受订单";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}


<section class="content-header">
    <h1><i class="fa fa-reorder"></i>接受订单</h1>
</section>
<section class="content">
    <div class="order-wrapper">
        <div class="order-title">
            @Html.Partial("ViewComponents/_OrderTitle")
        </div>
        <div class="order-content">
            @Html.Partial("ViewComponents/_OrderList", Model)
            <div class="order-list-contorl">
                每页 @Model.PageSize 条记录,共 @Model.Count 条记录,共 @Model.PageCount 页,当前第 @Model.PageNumber 页
                <div class="list-contorl-button">
                    @Html.PagedListPager(Model, page => Url.Action("ToAccept", new { page }))
                </div>
            </div>
        </div>
    </div>
</section>
@Html.Partial("ViewComponents/_ModifyRemark")
@Html.Partial("Admin/_ManageConfirm")
@section css{
    @Styles.Render("~/Css/Order/Orders.css")
}
@section scripts{
    @Scripts.Render("~/JS/Order/Orders.js")
}

Mall.Web.Back/Views/Order/ToDelivery.cshtml
@model PagedList.IPagedList<Mall.Web.Back.ViewModel.OrderViewModel>
@using PagedList.Mvc
@using PagedList

@{
    ViewBag.Title = "确认发货";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}


<section class="content-header">
    <h1><i class="fa fa-reorder"></i>确认发货</h1>
</section>
<section class="content">
    <div class="order-wrapper">
        <div class="order-title">
            @Html.Partial("ViewComponents/_OrderTitle")
        </div>
        <div class="order-content">
            @Html.Partial("ViewComponents/_OrderList", Model)
            <div class="order-list-contorl">
                每页 @Model.PageSize 条记录,共 @Model.Count 条记录,共 @Model.PageCount 页,当前第 @Model.PageNumber 页
                <div class="list-contorl-button">
                    @Html.PagedListPager(Model, page => Url.Action("AllOrders", new { page }))
                </div>
            </div>
        </div>
    </div>
</section>
@Html.Partial("ViewComponents/_ModifyRemark")
@Html.Partial("Admin/_ManageConfirm")
@section css{
    @Styles.Render("~/Css/Order/Orders.css")
}
@section scripts{
    @Scripts.Render("~/JS/Order/Orders.js")
}

Mall.Web.Back/Views/Order/ToReply.cshtml
@model PagedList.IPagedList<Mall.Web.Back.ViewModel.OrderViewModel>
@using PagedList.Mvc
@using PagedList

@{
    ViewBag.Title = "回复评价";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}


<section class="content-header">
    <h1><i class="fa fa-reorder"></i>待回复</h1>
</section>
<section class="content">
    <div class="order-wrapper">
        <div class="order-title">
            @Html.Partial("ViewComponents/_OrderTitle")
        </div>
        <div class="order-content">
            @Html.Partial("ViewComponents/_OrderList", Model)
            <div class="order-list-contorl">
                每页 @Model.PageSize 条记录,共 @Model.Count 条记录,共 @Model.PageCount 页,当前第 @Model.PageNumber 页
                <div class="list-contorl-button">
                    @Html.PagedListPager(Model, page => Url.Action("AllOrders", new { page }))
                </div>
            </div>
        </div>
    </div>
</section>
@Html.Partial("ViewComponents/_ModifyRemark")
@Html.Partial("Admin/_ManageConfirm")
@section css{
    @Styles.Render("~/Css/Order/Orders.css")
}
@section scripts{
    @Scripts.Render("~/JS/Order/Orders.js")
}