Mall.Web.Back/Controllers/StaffManageController.cs
using Mall.Service.DataBase;
using Mall.Service.Services;
using Mall.Service.Services.Enterprise;
using Mall.Web.Back.Filter;
using Mall.Web.Back.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mall.Web.Back.Controllers
{
    public class StaffManageController : Controller
    {
        private EnterpriseService _enterpriseService = new EnterpriseService();
        private UserService _userService = new UserService();
        private MenuViewService _menuViewService = new MenuViewService();

        /// <summary>
        /// 管理员详情(View)
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        [HttpGet]
        [PermissionAuthorize("DistributionAuthority")]
        public ActionResult EmployeeDetails(int userId)
        {
            User user = _enterpriseService.GetEmployeeByUserId(userId).User;
            UserViewModel employeeDTO = DataUserToDTO(user);
            return View(employeeDTO);
        }

        /// <summary>
        /// 管理员操作日志(View)
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        [HttpGet]
        [PermissionAuthorize("DistributionAuthority")]
        public ActionResult EmployeeActions(int userId)
        {
            Employee employee = _enterpriseService.GetEmployeeByUserId(userId);
            List<AdminLog> adminLogs = _enterpriseService.GetAdminLogsByEmployeeId(employee.EmployeeId);
            List<AdminLogViewModel> adminLogsDTO = new List<AdminLogViewModel>();
            foreach (var adminlog in adminLogs)
            {
                adminLogsDTO.Add(new AdminLogViewModel
                {
                    RecordId = adminlog.RecordId,
                    EmployeeId = adminlog.EmployeeId,
                    OperationTime = adminlog.OperationTime,
                    OperatDetail = adminlog.OperatDetail,
                    Operater = adminlog.Operater,
                    Object = adminlog.Object,
                    Permission = adminlog.Permission,
                    Style = adminlog.Style
                });
            };
            return PartialView(adminLogsDTO);
        }

        #region 员工管理
        /// <summary>
        /// 重名验证
        /// </summary>
        /// <param name="account"></param>
        /// <returns></returns>
        [HttpGet]
        public bool ReAccount(string account)
        {
            var result = _userService.ReName(account);
            return result;
        }

        /// <summary>
        /// 创建员工(View)
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [PermissionAuthorize("AddAdmin")]
        public ActionResult CreateEmployee()
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        /// <summary>
        /// 权限Menu
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [PermissionAuthorize("AddAdmin")]
        public JsonResult GetAllMenus()
        {
            List<PermissionsViewModel> menus = GetAllPermissionsMenu();
            JsonResult json = new JsonResult();
            json.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            json.Data = menus;
            return json;
        }

        /// <summary>
        /// 创建员工(Action)
        /// </summary>
        /// <param name="account"></param>
        /// <param name="logPassword"></param>
        /// <param name="phoneNumber"></param>
        /// <param name="birthday"></param>
        /// <param name="gender"></param>
        /// <param name="nick"></param>
        /// <param name="managePassword"></param>
        /// <param name="email"></param>
        /// <param name="permissionIds"></param>
        [HttpPost]
        [PermissionAuthorize("AddAdmin")]
        public bool CreateEmployee(string account, string logPassword, string phoneNumber,
                DateTime? birthday, bool gender = true, string nick = null,
                string managePassword = null, string email = null
                , int[] permissionIds = null)
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return false;
            }
            var result = _enterpriseService.CreateEmployee(employee.EmployeeId, account, logPassword, email,
                birthday, gender, nick, managePassword, phoneNumber, permissionIds);
            return result;
        }
        #endregion

        #region 权限/角色 管理
        [HttpGet]
        public ActionResult SearchEmployee(string search = "")
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            List<UserViewModel> users = _enterpriseService.GetAllEmployee()
                .Where(e => e.User.RealName.Contains(search) && e.EmployeeId != employee.EmployeeId)
                .Select(e => DataUserToDTO(e.User)).ToList();
            return View(users);
        }

        #region 权限
        /// <summary>
        /// 权限设置(View)
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [PermissionAuthorize("DistributionAuthority")]
        public ActionResult PermissionSet()
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        [PermissionAuthorize("DistributionAuthority")]
        public ActionResult GetEmployeePermissionsInfo(int userId)
        {
            Employee employee = _enterpriseService.GetEmployeeByUserId(userId);
            UserViewModel userDTO = DataUserToDTO(employee.User);
            return PartialView(userDTO);
        }

        [HttpGet]
        [PermissionAuthorize("DistributionAuthority")]
        public JsonResult GetPermissions(int userId)
        {
            Employee employee = _enterpriseService.GetEmployeeByUserId(userId);
            List<PermissionsViewModel> permissionsDTO = GetPermissionsMenuByEmployeeId(employee.EmployeeId);

            JsonResult json = new JsonResult();
            json.Data = permissionsDTO;
            json.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            return json;
        }

        [HttpGet]
        [PermissionAuthorize("DistributionAuthority")]
        public ActionResult GetEmployeePermissions(int userId)
        {
            Employee employee = _enterpriseService.GetEmployeeByUserId(userId);
            List<Permissions> permissions = _menuViewService.GetAllPermissionsByEmployeeId(employee.EmployeeId);
            List<PermissionsViewModel> permissionsDTO = permissions
                .Select(e => new PermissionsViewModel
                {
                    Id = e.PermissionId,
                    Name = e.Name,
                    Code = e.Code,
                    Details = e.Details,
                    CreationTime = e.CreationTime
                }).ToList();
            return PartialView(permissionsDTO);
        }

        [HttpPost]
        [PermissionAuthorize("DistributionAuthority")]
        public bool ModifyEmployeePermissions(int userId, int[] menuIds = null)
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return false;
            }
            bool result = _enterpriseService.ModifyPermissions(employee.EmployeeId, userId, menuIds);
            return result;
        }
        #endregion

        #region 角色
        /// <summary>
        /// 角色管理(View)
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [PermissionAuthorize("RoleManage")]
        public ActionResult RoleManage()
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return RedirectToAction("Index");
            }
            List<RolesViewModel> rolesDTO = _enterpriseService.GetRoles()
                .Select(r => new RolesViewModel
                {
                    Id = r.RoleId,
                    Code = r.Code,
                    CreationTime = r.CreationTime,
                    Name = r.Name,
                    Details = r.Details
                }).ToList();
            return View(rolesDTO);
        }

        /// <summary>
        /// 创建角色(Action)
        /// </summary>
        /// <param name="menuIds"></param>
        /// <param name="roleName"></param>
        /// <param name="roleDetails"></param>
        /// <returns></returns>
        [HttpPost]
        [PermissionAuthorize("RoleManage")]
        public bool CreateRole(int[] menuIds, string roleName, string roleDetails)
        {
            EmployeeViewModel employee = (EmployeeViewModel)Session["Employee"];
            if (employee == null)
            {
                return false;
            }
            var result = _enterpriseService.CreateRole(employee.EmployeeId, roleName, roleDetails, menuIds);
            return result;
        }

        [HttpGet]
        [PermissionAuthorize("RoleManage")]
        public JsonResult GetAllPermissions()
        {
            List<Menus> menus = _menuViewService.GetMenus().Where(m => m.IsDefault == false).ToList();
            List<PermissionsViewModel> permissionsDTO = menus.Select(m => new PermissionsViewModel
            {
                Id = m.MenuId,
                ParentId = m.ParentId,
                Name = m.MenuName,
                Code = m.MenuPath,
                Has = false,
                IsDefault = false,
            }).ToList();

            JsonResult json = new JsonResult();

Mall.Web.Back/Views/StaffManage/CreateEmployee.cshtml
@{
    ViewBag.Title = "新增管理员";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}
<section class="content-header">
    <h1><i class="fa fa-plus-square"></i>新增管理员</h1>
</section>
<section class="content">
    <div class="create-employee-all">
        <form name="createEmployee" id="createEmployee" action="CreateEmployee">
            <table>
                <tbody>
                    <tr>
                        <td>
                            <div class="create-employee-left">
                                <div class="create-employee-left-title">
                                    <p class="title">基本信息</p><span class="star">*</span><span>为必填项</span>
                                </div>
                                <div class="create-employee-left-account info">
                                    <p class="title"><span class="star">*</span>账户</p>
                                    <input name="account" id="account" type="text" />
                                </div>
                                <div class="create-employee-left-nick info">
                                    <p class="title">昵称</p>
                                    <input name="nick" id="nick" type="text" /><span>(默认与账户相同)</span>
                                </div>
                                <div class="create-employee-left-birthday info">
                                    <p class="title">生日</p>
                                    <input name="birthday" id="birthday" type="date" min="1900-1-1" max="@DateTime.Now" />
                                </div>
                                <div class="create-employee-left-gender info">
                                    <p class="title">性别</p>
                                    <label><input name="gender" type="radio" value="1"/>男</label>
                                    <label><input name="gender" type="radio" value="0"/>女</label>
                                </div>
                                <div class="create-employee-left-log-password info">
                                    <p class="title"><span class="star">*</span>登录密码</p>
                                    <input name="logPassword" id="logPassword" type="password" />
                                </div>
                                <div class="create-employee-left-manage-password info">
                                    <p class="title">管理密码</p>
                                    <input name="managePassword" id="managePassword" type="password" /><span>(默认与登录密码相同)</span>
                                </div>
                                <div class="create-employee-left-phone info">
                                    <p class="title">联系电话</p>
                                    <input name="phoneNumber" id="phoneNumber" type="text" maxlength="11" />
                                </div>
                                <div class="create-employee-left-email info">
                                    <p class="title"><span class="star">*</span>E-mail</p>
                                    <input name="email" id="email" type="email" />
                                </div>
                                <div class="create-employee-left-submit info">
                                    <button type="button" onclick="CreateEmployee()">添加管理员</button>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="create-employee-right">
                                <div class="creat-employee-right-title">
                                    <p class="title">权限设置</p>
                                </div>
                                <div class="create-employee-right-permissions">
                                    <ul id="permissionsTree" class="ztree"></ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</section>
@Html.Partial("Admin/_ManageConfirm")
@section css{
    @Styles.Render("~/Css/StaffManage/CreateEmployee.css")
    @Styles.Render("~/Css/Shared/zTreeStyle.css")
}
@section scripts{
    @Scripts.Render("~/JS/StaffManage/PermissionSet.js")
    @Scripts.Render("~/JS/StaffManage/CreateEmployee.js")
    @Scripts.Render("~/JS/Shared/jquery.ztree.all.js")
}

Mall.Web.Back/Views/StaffManage/EmployeeActions.cshtml
@model List<Mall.Web.Back.ViewModel.AdminLogViewModel>

<div class="employee-action-title">
    <ul>
        <li class="action-handle">操作者</li>
        <li class="action-time">时间</li>
        <li class="action-style">类型</li>
        <li class="action-permission">使用权限</li>
        <li class="action-object">操作对象</li>
        <li class="action-detail">详情</li>
    </ul>
</div>
<div class="employee-action-content">
    <ul>
        @{
            if (Model.Count == 0)
            {
                <li class="action-item even no-action">该员工暂未进行任何操作…………</li>
            }
            else
            {
                for (var i = 0; i < Model.Count; i++)
                {
                    <li class="action-item @(i % 2 == 0 ? "even" : "odd") ">
                        <ul>
                            <li class="action-handle" title="@Model[i].Operater">@(Model[i].Operater.Length >= 8 ? Model[i].Operater.Substring(0, 7) + "…" : Model[i].Operater)</li>
                            <li class="action-time" title="@Model[i].OperationTime">@Model[i].OperationTime.ToString().Substring(0, 9) …</li>
                            <li class="action-style" title="@Model[i].Style">@(Model[i].Style.Length >= 5 ? Model[i].Style.Substring(0, 4) + "…" : Model[i].Style)</li>
                            <li class="action-permission" title="@Model[i].Permission">@(Model[i].Permission.Length >= 5 ? Model[i].Permission.Substring(0,4) + "…" : Model[i].Permission)</li>
                            <li class="action-object" title="@Model[i].Object">@(Model[i].Object.Length >= 6 ? Model[i].Object.Substring(0, 5) + "…" : Model[i].Object)</li>
                            <li class="action-detail" title="@Model[i].OperatDetail">@(Model[i].OperatDetail.Length >= 36 ? Model[i].OperatDetail.Substring(0,35) + "…" : Model[i].OperatDetail)</li>
                        </ul>
                    </li>
                }
            }
        }
    </ul>
</div>

Mall.Web.Back/Views/StaffManage/EmployeeDetails.cshtml
@model Mall.Web.Back.ViewModel.UserViewModel

@{
    ViewBag.Title = "管理员详情";
    Layout = "~/Views/Layout/_Layout.cshtml";
}

<section class="content-header">
    <h2><i class="fa fa-file-text-o"></i>管理员详情</h2>
</section>
<section class="content">
    <div class="employee-info">
        <table>
            <tbody>
                <tr>
                    <td class="info-basic">
                        <div class="employee-info-basic">
                            <div class="info-basic-img">
                                <p class="title">头像</p>
                                <div class="img-photo-image">
                                    <img src="@Model.Photo" />
                                </div>
                            </div>
                            <table>
                                <tbody class="info-basic-content">
                                    <tr>
                                        <td>管理员Id</td>
                                        <td class="Data">@Model.UserId</td>
                                        <td>账户</td>
                                        <td class="Data">@Model.Account</td>
                                    </tr>
                                    <tr>
                                        <td>昵称</td>
                                        <td class="Data">@Model.NickName</td>
                                        <td>真实姓名</td>
                                        <td class="Data">@Model.RealName</td>
                                    </tr>
                                    <tr>
                                        <td>联系电话</td>
                                        <td class="Data">@Model.PhoneNumber</td>
                                        <td>E-mail</td>
                                        <td class="Data">@Model.Email</td>
                                    </tr>
                                    <tr>
                                        <td>性别</td>
                                        <td class="Data">@(Model.Gender == true ? "男" : "女")</td>
                                        <td>出生日期</td>
                                        <td class="Data">@Model.Birthday</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </td>
                    <td class="info-permission">
                        <div class="employee-info-permission">
                            <div class="title">
                                <p>权限</p>
                            </div>
                            <div class="permission">
                                @Html.Action("GetEmployeePermissions", "StaffManage", new { employeeId = Model.UserId })
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="employee-action">
        <h3>管理员日志</h3>
        @Html.Action("EmployeeActions", "StaffManage", new { userId = Model.UserId })
    </div>
</section>
@section css{
    @Styles.Render("~/Css/StaffManage/EmployeeDetails.css")
    @Styles.Render("~/Css/StaffManage/EmployeePermissions.css")
}

Mall.Web.Back/Views/StaffManage/GetEmployeePermissions.cshtml
@model List<Mall.Web.Back.ViewModel.PermissionsViewModel>

<div class="permission-title">
    <ul>
        <li class="permission-name">权限名称</li>
        <li class="permission-detail">权限简介</li>
        <li class="permission-time">授权时间</li>
    </ul>
</div>
<div class="permission-content">
    <ul>
        @if (Model.Count != 0)
        {
            for (var i = 0; i < Model.Count; i++)
            {
                <li class="permission-item @(i % 2 == 0 ? "even" : "odd")">
                    <ul>
                        <li class="permission-name">@Model[i].Name</li>
                        <li class="permission-detail" title="@Model[i].Details">@(Model[i].Details.ToString().Length >= 30 ? Model[i].Details.ToString().Substring(0,29) + "…" : Model[i].Details)</li>
                        <li class="permission-time">@Model[i].CreationTime</li>
                    </ul>
                </li>
            }
        }
        else
        {
            <li class="permission-item even">该员工暂无权限</li>
        }
    </ul>
</div>

Mall.Web.Back/Views/StaffManage/GetEmployeePermissionsInfo.cshtml
@model Mall.Web.Back.ViewModel.UserViewModel

@Html.Partial("ViewComponents/_GetEmployeeInfo", Model)
<div class="admin-detail-permission">
    <div class="employee-info-permission">
        <div class="permission-list">
            <p class="title">权限</p>
            <div class="permission">
                @Html.Action("GetEmployeePermissions", "StaffManage", new { userId = Model.UserId })
            </div>
        </div>
    </div>
    <div class="permission-submit">
        <button type="button" onclick="GetPermissionMenus()">修改权限</button>
    </div>
</div>

Mall.Web.Back/Views/StaffManage/GetEmployeeRolesInfo.cshtml
@model Mall.Web.Back.ViewModel.UserViewModel

@Html.Partial("ViewComponents/_GetEmployeeInfo", Model)
<div class="admin-detail-permission">
    <div class="employee-info-permission">
        <div class="permission-list">
            <p class="title">角色</p>
            <div class="permission">
                @Html.Action("GetEmployeeRoles", "StaffManage", new { userId = Model.UserId })
            </div>
        </div>
    </div>
    <div class="permission-submit">
        <button type="button" onclick="GetRoleMenus()">修改角色</button>
    </div>
</div>

Mall.Web.Back/Views/StaffManage/PermissionSet.cshtml
@{
    ViewBag.Title = "权限设置";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}

<section class="content-header">
    <h1><i class="fa fa-cog"></i>权限设置</h1>
</section>
<section class="content">
    <div class="role-wrapper">
        <div class="search-content">
            <input id="search-input" type="text" />
            <button type="button" onclick="SearchEmployee()">搜索</button>
        </div>
        <div class="admin-content">
            <table>
                <tbody>
                    <tr>
                        <td>
                            <div class="admin" id="admin-list">
                                @Html.Action("SearchEmployee", "StaffManage", new { search = string.Empty })
                            </div>
                        </td>
                        <td>
                            <div class="admin-detail" id="admin-detail">
                                @Html.Partial("ViewComponents/_GetEmployeeInfo", new Mall.Web.Back.ViewModel.UserViewModel())
                                <div class="admin-detail-permission">
                                    <div class="permission-list">
                                        <div class="employee-info-permission">
                                            <p class="title">权限</p>
                                            <div class="permission">
                                                <div class="permission-title">
                                                    <ul>
                                                        <li class="permission-name">权限名称</li>
                                                        <li class="permission-detail">权限简介</li>
                                                        <li class="permission-time">授权时间</li>
                                                    </ul>
                                                </div>
                                                <div class="permission-content">
                                                    <ul>
                                                        <li class="permission-item even">请选择员工</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="permission-submit">
                                            <button style="cursor:no-drop;" type="button" disabled="disabled" title="未选择员工，不可修改">修改权限</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</section>
@Html.Partial("ViewComponents/_ModifyPermissions")
@section css{
    @Styles.Render("~/Css/StaffManage/PermissionSet.css")
    @Styles.Render("~/Css/StaffManage/EmployeePermissions.css")
    @Styles.Render("~/Css/Shared/zTreeStyle.css")
}
@section scripts{
    @Scripts.Render("~/JS/StaffManage/PermissionSet.js")
    @Scripts.Render("~/JS/Shared/jquery.ztree.all.js")
    <script>
        function Refresh(event) {
            var id = event.id;
            $.ajax({
                type: 'Get',
                url: '/StaffManage/GetEmployeePermissionsInfo',
                data: { "userId": id },
                datatype: 'html',
                beforeSend: function () {
                    layer.load(2, {
                        shade: [0.1, '#fff'] //0.1透明度的白色背景
                    });
                },
                success: function (html) {
                    $("#admin-detail").html(html);
                    layer.closeAll("loading");
                },
                error: function () {
                    layer.closeAll("loading");
                    OpenTip("出错啦!", 1);
                }
            });
        }
    </script>
}

Mall.Web.Back/Views/StaffManage/RoleManage.cshtml
@model List<Mall.Web.Back.ViewModel.RolesViewModel>

@{
    ViewBag.Title = "角色管理";
    Layout = "~/Views/Layout/_AdminTLE.cshtml";
}

<section class="content-header">
    <h1><i class="fa fa-cog"></i>角色管理</h1>
</section>
<section class="content">
    <div class="role-wrapper">
        <div class="search-content">
            <input id="search-input" type="text" />
            <button type="button" onclick="SearchEmployee()">搜索</button>
        </div>
        <div class="admin-content">
            <table>
                <tbody>
                    <tr>
                        <td>
                            <div class="admin" id="admin-list">
                                @Html.Action("SearchEmployee", "StaffManage", new { search = string.Empty })
                            </div>
                        </td>
                        <td>
                            <div class="admin-detail" id="admin-detail">
                                @Html.Partial("ViewComponents/_GetEmployeeInfo", new Mall.Web.Back.ViewModel.UserViewModel())
                                <div class="admin-detail-permission">
                                    <div class="permission-list">
                                        <div class="employee-info-permission">
                                            <p class="title">角色</p>
                                            <div class="permission">
                                                <div class="permission-title">
                                                    <ul>
                                                        <li class="permission-name">角色名称</li>
                                                        <li class="permission-detail">角色简介</li>
                                                        <li class="permission-time">授权时间</li>
                                                    </ul>
                                                </div>
                                                <div class="permission-content">
                                                    <ul>
                                                        <li class="permission-item even">请选择员工</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="permission-submit">
                                            <button style="cursor:no-drop;" type="button" disabled="disabled" title="未选择员工，不可修改">修改角色</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="role-manage">
            @Html.Partial("GetEmployeeRoles",Model)
            <button type="button"onclick="CreateRole()">新建角色</button>
        </div>
    </div>
    <div id="click-menu">
        <p>编辑角色</p>
        <ul>
            <li id="addItem" onclick="DeletRole()">
                删除角色
            </li>
            <li onclick="ModifyRole()">修改角色</li>
        </ul>
    </div>
</section>
@Html.Partial("ViewComponents/_ModifyEmployeeRoles")
@Html.Partial("ViewComponents/_CreateRole")
@Html.Partial("ViewComponents/_ModifyRolePermissions")
@section css{
    @Styles.Render("~/Css/StaffManage/RoleManage.css")
    @Styles.Render("~/Css/StaffManage/PermissionSet.css")
    @Styles.Render("~/Css/StaffManage/EmployeePermissions.css")
    @Styles.Render("~/Css/Shared/zTreeStyle.css")
}
@section scripts{
    @Scripts.Render("~/JS/StaffManage/RoleManage.js")
    @Scripts.Render("~/JS/StaffManage/PermissionSet.js")
    @Scripts.Render("~/JS/Shared/jquery.ztree.all.js")
    <script>
        function Refresh(event) {
            var id = event.id;
            $.ajax({
                type: 'Get',
                url: '/StaffManage/GetEmployeeRolesInfo',
                data: { "userId": id },
                datatype: 'html',
                beforeSend:function(){
                    layer.load(1, {
                        shade: [0.1, '#fff'] //0.1透明度的白色背景
                    });
                },
                success: function (html) {
                    $("#admin-detail").html(html);
                    layer.closeAll("loading");
                },
                error: function () {
                    OpenTip("出错啦!", 1);
                    layer.closeAll("loading");
                }
            });
        }
    </script>
}